version: "3.2"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "8085:80"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hackathon
      - MYSQL_ROOT_PASSWORD=hackathon
